parameters:
# ... some parameters

services:
#    Пользователи
#    sonata.user.admin.user:
#        class: "%sonata.user.admin.user.class%"
#        public: true
#        calls:
#            - [setTranslationDomain, ['%sonata.user.admin.user.translation_domain%']]
#        arguments: [~, "%sonata.user.admin.user.entity%", "%sonata.user.admin.user.controller%"]
#        tags:
#              - { name: sonata.admin, manager_type: orm, label: users, label_catalogue: "%sonata.user.admin.label_catalogue%", group: "%sonata.user.admin.groupname%", label_translator_strategy: "sonata.admin.label.strategy.underscore",  show_in_dashboard: true, icon: '<i class="fa fa-users"></i>'}
#
##    Пользователи
#    sonata.user.admin.group:
#        class: "%sonata.user.admin.group.class%"
#        public: true
#        calls:
#            - [setTranslationDomain, ['%sonata.user.admin.group.translation_domain%']]
#        arguments: [~, "%sonata.user.admin.group.entity%", "%sonata.user.admin.group.controller%"]
#        tags:
#              - { name: sonata.admin, manager_type: orm, label: groups, label_catalogue: "%sonata.user.admin.label_catalogue%", group: "%sonata.user.admin.groupname%", label_translator_strategy: "sonata.admin.label.strategy.underscore",  show_in_dashboard: true, icon: '<i class="fa fa-users"></i>'}
#   Каталог
    App\Admin\CardAdmin:
        arguments:
            - ~
            - App\Entity\Card
            - App\Controller\Admin\CardAdminController
            - '@App\Service\FieldDescriptionService'
            - '@App\Service\TopMenuButtonService'
            - '@App\Service\AdminRouteService'
        tags:
            - { name: sonata.admin, manager_type: orm, label: Поиск оборудования, group: Каталог, show_in_dashboard: true, icon: '<i class="fa fa-newspaper-o"></i>'}
#   Каталог
    App\Admin\CardFieldsOptionAdmin:
        arguments: [~, App\Entity\CardFieldsOption, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Дополнительные поля, group: Каталог, show_in_dashboard: true}
#   Документы
    App\Admin\ArrivalAdmin:
        arguments: [~, App\Entity\Arrival, App\Controller\Admin\ArrivalAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Приход, group: Документы, show_in_dashboard: true, icon: '<i class="fa fa-file-excel-o"></i>'}
    App\Admin\ReferenceDashboardAdmin:
        arguments: [~, App\Entity\Arrival, App\Controller\Admin\ReferenceDashboardController]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Настройки, group: Каталог, show_in_dashboard: true, icon: '<i class="fa fa-file-excel-o"></i>'}
    App\Admin\MarkingAdmin:
        arguments:
            - ~
            - App\Entity\Marking
            - App\Controller\Admin\MarkingAdminController
            - "@Symfony\\Component\\Security\\Core\\Security"
            - '@App\Service\Access\RoleService'
            - '@App\Service\Marking\TaskTopMenuButtonService'
        tags:
            - { name: sonata.admin, manager_type: orm, label: Маркировка, group: Задания, show_in_dashboard: true}
    App\Admin\TaskDashboardAdmin:
        arguments: [~, App\Entity\TaskDashboard, App\Controller\Admin\TaskDashboardController]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Создать задание, group: Задания, show_in_dashboard: true}
    App\Admin\InventoryAdmin:
        arguments:
            - ~
            - App\Entity\Inventory
            - App\Controller\Admin\InventoryAdminController
            - "@Symfony\\Component\\Security\\Core\\Security"
            - '@App\Service\Access\RoleService'
            - '@App\Service\Marking\TaskTopMenuButtonService'
        tags:
            - { name: sonata.admin, manager_type: orm, label: Инвентаризация, group: Задания, show_in_dashboard: true}
    App\Admin\InspectionAdmin:
        arguments:
            - ~
            - App\Entity\Inspection
            - App\Controller\Admin\InspectionAdminController
            - "@Symfony\\Component\\Security\\Core\\Security"
            - '@App\Service\Access\RoleService'
            - '@App\Service\Marking\TaskTopMenuButtonService'
        tags:
            - { name: sonata.admin, manager_type: orm, label: Инспекция, group: Задания, show_in_dashboard: true}
    App\Admin\Equipment\EquipmentAdmin:
        arguments:
            - ~
            - App\Entity\Equipment
            - App\Controller\Admin\EquipmentAdminController
            - "@Symfony\\Component\\Security\\Core\\Security"
            - '@App\Service\Access\RoleService'
            - '@App\Service\Marking\TaskTopMenuButtonService'
        tags:
            - { name: sonata.admin, manager_type: orm, label: Комплектация, group: Задания, show_in_dashboard: true}
    App\Admin\Equipment\EquipmentKitSpecificationAdmin:
        arguments:
            - ~
            - App\Entity\EquipmentKitSpecification
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: Характеристики для комплекта, group: Комплектация, show_in_dashboard: false}
    App\Admin\ReturnFromRentAdmin:
        arguments:
            - ~
            - App\Entity\ReturnFromRent
            - App\Controller\Admin\ReturnFromRentAdminController
            - "@Symfony\\Component\\Security\\Core\\Security"
            - '@App\Service\Access\RoleService'
            - '@App\Service\Marking\TaskTopMenuButtonService'
        tags:
            - { name: sonata.admin, manager_type: orm, label: Возврат из аренды, group: Задания, show_in_dashboard: true}
    App\Admin\RepairAdmin:
        arguments:
            - ~
            - App\Entity\Repair
            - App\Controller\Admin\RepairAdminController
            - "@Symfony\\Component\\Security\\Core\\Security"
            - '@App\Service\Access\RoleService'
            - '@App\Service\Marking\TaskTopMenuButtonService'
        tags:
            - { name: sonata.admin, manager_type: orm, label: Комплектация в ремонт, group: Задания, show_in_dashboard: true}
    App\Admin\ReturnFromRepairAdmin:
        arguments:
            - ~
            - App\Entity\ReturnFromRepair
            - App\Controller\Admin\ReturnFromRepairAdminController
            - "@Symfony\\Component\\Security\\Core\\Security"
            - '@App\Service\Access\RoleService'
            - '@App\Service\Marking\TaskTopMenuButtonService'
        tags:
            - { name: sonata.admin, manager_type: orm, label: Возврат из ремонта, group: Задания, show_in_dashboard: true}
    App\Admin\KitAdmin:
        arguments:
            - ~
            - App\Entity\Kit
            - App\Controller\Admin\ReturnFromRepairAdminController
        tags:
            - { name: sonata.admin, manager_type: orm, label: Комплект для постановщика, group: Каталог, show_in_dashboard: true}
    App\Admin\CardTemporaryAdmin:
        arguments:
            - ~
            - App\Entity\CardTemporary
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: Временная карточка, group: Каталог, show_in_dashboard: true}
    App\Admin\LogApiAdmin:
        arguments:
            - ~
            - App\Entity\LogApi
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: Апи, group: Лог, show_in_dashboard: false}
