parameters:
# ... some parameters

services:
    App\Admin\CardAdmin:
        arguments: [~, App\Entity\Card, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Карточка, group: Карточка, show_in_dashboard: true, icon: '<i class="fa fa-newspaper-o"></i>'}
    App\Admin\CardFieldsOptionAdmin:
        arguments: [~, App\Entity\CardFieldsOption, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Дополнительные поля, group: Карточка, show_in_dashboard: true}
    App\Admin\ArrivalAdmin:
        arguments: [~, App\Entity\Arrival, App\Controller\Admin\ArrivalAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Приход, group: Приход, show_in_dashboard: true, icon: '<i class="fa fa-file-excel-o"></i>'}