#https://github.com/simplethings/EntityAuditBundle/blob/1.0/README.md
simple_things_entity_audit:
    audited_entities:
        - App\Entity\Card
        - App\Entity\CardFields
        - App\Entity\TaskCardOtherField
        - App\Entity\Marking
        - App\Entity\Inventory
        - App\Entity\Inspection
        - App\Entity\Equipment
        - App\Entity\ReturnFromRent
        - App\Entity\Repair
        - App\Entity\ReturnFromRepair