sonata_user:
    security_acl: true
    manager_type: orm
    mailer: fos_user.mailer.noop
    class:
        user: App\Entity\User
        group: App\Entity\Group
    admin:                  # Admin Classes
        user:
            class:          App\Admin\UserAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle

        group:
            class:          Sonata\UserBundle\Admin\Entity\GroupAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle