# https://symfony.com/doc/master/bundles/SonataAdminBundle/reference/configuration.html
sonata_admin:
    title: 'Temerso'
    templates:
        # пример перезаписи
#        show: '@SonataAdmin/CRUD/show.html.twig'
        show:    /crud/show.html.twig
#        history: /crud/history.html.twig
        show_compare: '/crud/show_compare.html.twig'

        user_block: '@SonataAdmin/Core/user_block.html.twig'
        add_block: '@SonataAdmin/Core/add_block.html.twig'
        layout: '@SonataAdmin/standard_layout.html.twig'
        ajax: '@SonataAdmin/ajax_layout.html.twig'
        dashboard: '@SonataAdmin/Core/dashboard.html.twig'
        search: '@SonataAdmin/Core/search.html.twig'
        list: '@SonataAdmin/CRUD/list.html.twig'
        filter: '@SonataAdmin/Form/filter_admin_fields.html.twig'
#        show_compare: '@SonataAdmin/CRUD/show_compare.html.twig'
        edit: '@SonataAdmin/CRUD/edit.html.twig'
        preview: '@SonataAdmin/CRUD/preview.html.twig'
        history: '@SonataAdmin/CRUD/history.html.twig'
        acl: '@SonataAdmin/CRUD/acl.html.twig'
        history_revision_timestamp: '@SonataAdmin/CRUD/history_revision_timestamp.html.twig'
        action: '@SonataAdmin/CRUD/action.html.twig'
        select: '@SonataAdmin/CRUD/list__select.html.twig'
        list_block: '@SonataAdmin/Block/block_admin_list.html.twig'
        search_result_block: '@SonataAdmin/Block/block_search_result.html.twig'
        short_object_description: '@SonataAdmin/Helper/short-object-description.html.twig'
        delete: '@SonataAdmin/CRUD/delete.html.twig'
        batch: '@SonataAdmin/CRUD/list__batch.html.twig'
        batch_confirmation: '@SonataAdmin/CRUD/batch_confirmation.html.twig'
        inner_list_row: '@SonataAdmin/CRUD/list_inner_row.html.twig'
        outer_list_rows_mosaic: '@SonataAdmin/CRUD/list_outer_rows_mosaic.html.twig'
        outer_list_rows_list: '@SonataAdmin/CRUD/list_outer_rows_list.html.twig'
        outer_list_rows_tree: '@SonataAdmin/CRUD/list_outer_rows_tree.html.twig'
        base_list_field: '@SonataAdmin/CRUD/base_list_field.html.twig'
        pager_links: '@SonataAdmin/Pager/links.html.twig'
        pager_results: '@SonataAdmin/Pager/results.html.twig'
        tab_menu_template: '@SonataAdmin/Core/tab_menu_template.html.twig'
        knp_menu_template: '@SonataAdmin/Menu/sonata_menu.html.twig'

    assets:
        extra_stylesheets:
            - general.css
    dashboard:
        blocks:
#            - { type: sonata.admin.block.admin_list, position: left }
            -
                class:    col-lg-3 col-xs-6
                position: top
                type:     sonata.admin.block.stats
                settings:
#                    code: sonata.user.admin.card
                    code: App\Admin\ArrivalAdmin
                    icon: fa-file-excel-o
                    text: Приход
                    filters:
                        status: { type: 3, value: 0 }
            -
                class:    col-lg-3 col-xs-6
                position: top
                type:     sonata.admin.block.stats
                settings:
#                    code: sonata.user.admin.card
                    code: App\Admin\CardAdmin
                    icon: fa-newspaper-o
                    text: Количество карточек
                    filters:
                        status: { type: 3, value: 0 }
            -
                class:    col-lg-3 col-xs-6
                position: top
                type:     sonata.admin.block.stats
                settings:
                    code: sonata.user.admin.user
                    icon: fa-users
                    text: Список пользователей
                    color: bg-green
                    filters:
                        status: { type: 3, value: 0 }

            -
                class:    col-lg-3 col-xs-6
                position: top
                type:     sonata.admin.block.stats
                settings:
                    code:  sonata.user.admin.group
                    icon:  fa-group
                    text:  Список ролей
                    color: bg-green
    options:
        legacy_twig_text_extension: false
    security:
        handler: sonata.admin.security.handler.acl

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
