sonata_admin:
    title: 'Temerso'
    templates:
        # default global templates
        # the layout template include javascript/stylesheet to the formatter bundle,
        # if you don't need it use the default one: SonataAdminBundle::standard_layout.html.twig
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default value if done set, actions templates, should extends a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    /crud/show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
    dashboard:
        blocks:
#            - { type: sonata.admin.block.admin_list, position: left }
            -
                class:    col-lg-3 col-xs-6
                position: top
                type:     sonata.admin.block.stats
                settings:
#                    code: sonata.user.admin.card
                    code: App\Admin\ArrivalAdmin
                    icon: fa-file-excel-o
                    text: Приход
                    filters:
                        status: { type: 3, value: 0 }
            -
                class:    col-lg-3 col-xs-6
                position: top
                type:     sonata.admin.block.stats
                settings:
#                    code: sonata.user.admin.card
                    code: App\Admin\CardAdmin
                    icon: fa-newspaper-o
                    text: Количество карточек
                    filters:
                        status: { type: 3, value: 0 }
            -
                class:    col-lg-3 col-xs-6
                position: top
                type:     sonata.admin.block.stats
                settings:
                    code: sonata.user.admin.user
                    icon: fa-users
                    text: Список пользователей
                    color: bg-green
                    filters:
                        status: { type: 3, value: 0 }

            -
                class:    col-lg-3 col-xs-6
                position: top
                type:     sonata.admin.block.stats
                settings:
                    code:  sonata.user.admin.group
                    icon:  fa-group
                    text:  Список ролей
                    color: bg-green
    options:
        legacy_twig_text_extension: false
    security:
        handler: sonata.admin.security.handler.acl

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
