# https://symfony.com/doc/master/bundles/SonataAdminBundle/reference/configuration.html
sonata_admin:
#    title: 'Temerso'
    title: false
    title_logo: img/logo.png
    templates:
        # пример перезаписи
        #        show: '@SonataAdmin/CRUD/show.html.twig'
        show:    /crud/show.html.twig
        #        history: /crud/history.html.twig
        show_compare: '/crud/show_compare.html.twig'
        layout: 'standard_layout.html.twig'
        list: 'crud/list.html.twig'
        edit: 'crud/edit.html.twig'
        history: 'crud/history.html.twig'

#        user_block: '@SonataAdmin/Core/user_block.html.twig'
        add_block: '@SonataAdmin/Core/add_block.html.twig'
#        layout: '@SonataAdmin/standard_layout.html.twig'
        ajax: '@SonataAdmin/ajax_layout.html.twig'
        dashboard: '@SonataAdmin/Core/dashboard.html.twig'
        search: '@SonataAdmin/Core/search.html.twig'
#        list: '@SonataAdmin/CRUD/list.html.twig'
        filter: '@SonataAdmin/Form/filter_admin_fields.html.twig'
        #        show_compare: '@SonataAdmin/CRUD/show_compare.html.twig'
#        edit: '@SonataAdmin/CRUD/edit.html.twig'
        preview: '@SonataAdmin/CRUD/preview.html.twig'
#        history: '@SonataAdmin/CRUD/history.html.twig'
        acl: '@SonataAdmin/CRUD/acl.html.twig'
        history_revision_timestamp: '@SonataAdmin/CRUD/history_revision_timestamp.html.twig'
        action: '@SonataAdmin/CRUD/action.html.twig'
        select: '@SonataAdmin/CRUD/list__select.html.twig'
        list_block: '@SonataAdmin/Block/block_admin_list.html.twig'
        search_result_block: '@SonataAdmin/Block/block_search_result.html.twig'
        short_object_description: '@SonataAdmin/Helper/short-object-description.html.twig'
        delete: '@SonataAdmin/CRUD/delete.html.twig'
        batch: '@SonataAdmin/CRUD/list__batch.html.twig'
        batch_confirmation: '@SonataAdmin/CRUD/batch_confirmation.html.twig'
        inner_list_row: '@SonataAdmin/CRUD/list_inner_row.html.twig'
        outer_list_rows_mosaic: '@SonataAdmin/CRUD/list_outer_rows_mosaic.html.twig'
        outer_list_rows_list: '@SonataAdmin/CRUD/list_outer_rows_list.html.twig'
        outer_list_rows_tree: '@SonataAdmin/CRUD/list_outer_rows_tree.html.twig'
        base_list_field: '@SonataAdmin/CRUD/base_list_field.html.twig'
        pager_links: '@SonataAdmin/Pager/links.html.twig'
        pager_results: '@SonataAdmin/Pager/results.html.twig'
        tab_menu_template: '@SonataAdmin/Core/tab_menu_template.html.twig'
        knp_menu_template: '@SonataAdmin/Menu/sonata_menu.html.twig'

    assets:
        stylesheets:
            - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-red.min.css

            # The default stylesheet list:
            - bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css
            - bundles/sonatacore/vendor/components-font-awesome/css/font-awesome.min.css
            - bundles/sonatacore/vendor/ionicons/css/ionicons.min.css
            - bundles/sonataadmin/vendor/admin-lte/dist/css/AdminLTE.min.css
#            - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-black.min.css
            - bundles/sonataadmin/vendor/iCheck/skins/square/blue.css
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
            - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css
            - bundles/sonatacore/vendor/select2/select2.css
            - bundles/sonatacore/vendor/select2-bootstrap-css/select2-bootstrap.min.css
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
            - bundles/sonataadmin/css/styles.css
            - bundles/sonataadmin/css/layout.css
            - bundles/sonataadmin/css/tree.css
            - bundles/sonataadmin/css/colors.css
        extra_stylesheets:
            - css/general.css
            - css/theme-config.css
            - css/plugin/bootstrap-dialog.min.css

        extra_javascripts:
            - js/plugin/bootstrap-dialog.min.js
    dashboard:
        blocks:
            #            - { type: sonata.admin.block.admin_list, position: left }
            -   class:    col-lg-3 col-xs-6
                position: top
                type:     sonata.admin.block.stats
                settings:
                    #                    code: sonata.user.admin.card
                    code: App\Admin\ArrivalAdmin
                    icon: fa-file-excel-o
                    text: Приход
                    color: temerso-color
                    filters:
                        status: { type: 3, value: 0 }
            -   class:    col-lg-3 col-xs-6
                position: top
                type:     sonata.admin.block.stats
                settings:
                    #                    code: sonata.user.admin.card
                    code: App\Admin\CardAdmin
                    icon: fa-newspaper-o
                    text: Количество карточек
                    color: temerso-color
                    filters:
                        status: { type: 3, value: 0 }
            -   class:    col-lg-3 col-xs-6
                position: top
                type:     sonata.admin.block.stats
                settings:
                    code: sonata.user.admin.user
                    icon: fa-users
                    text: Список пользователей
                    color: temerso-color
                    filters:
                        status: { type: 3, value: 0 }

            -   class:    col-lg-3 col-xs-6
                position: top
                type:     sonata.admin.block.stats
                settings:
                    code:  sonata.user.admin.group
                    icon:  fa-group
                    text:  Список ролей
                    color: temerso-color

        groups:
            user:
                label:                "sonata_user"
                label_catalogue:      "SonataUserBundle"
                icon: '<i class="fa fa-users"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
            card:
                label: "Каталог"
                icon: '<i class="fa fa-newspaper-o"></i>'
                items:
                    - App\Admin\CardAdmin
                    - label: "База списанного оборудования"
                      route: admin_empty
                      roles: [ROLE_ADMIN]
                    - label: "Аналитика"
                      route: admin_empty
                      roles: [ROLE_ADMIN]
                    - App\Admin\ReferenceDashboardAdmin
            cardDashboardRef:
                items:
                    - App\Admin\Reference\RefInnerCoatingAdmin
                    - App\Admin\Reference\RefHardbandingNippleAdmin
                    - App\Admin\Reference\RefTypeThreadAdmin
                    - App\Admin\Reference\RefWarehouseAdmin
            cardDashboardFields:
                items:
                    - App\Admin\CardFieldsOptionAdmin
            taskDashboard:
                items:
                    - App\Admin\MarkingAdmin

            task:
                label: "Задания"
                items:
#                    - App\Admin\TaskDashboardAdmin
                    - label: "Создать задание"
                      route: admin_app_taskdashboard_task_create
                      roles: [ROLE_ADMIN]
                    - label: "Все задания"
                      route: admin_app_taskdashboard_task_list
                      roles: [ROLE_APP\ADMIN\MARKINGADMIN_GUEST]
                    - label: "Ожидающие проверки"
                      route: admin_app_taskdashboard_task_list_check
                      roles: [ROLE_ADMIN]
                    - label: "Аналитика"
                      route: admin_empty
                      roles: [ROLE_ADMIN]
            document:
                label: "Документы"
                items:
                    - App\Admin\ArrivalAdmin
                    - label: "Выгрузка документов"
                      route: admin_empty
                      roles: [ROLE_ADMIN]
                    - label: "Аналитика"
                      route: admin_empty
                      roles: [ROLE_ADMIN]

    options:
        legacy_twig_text_extension: false
    security:
        handler: sonata.admin.security.handler.acl

        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN

        # acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]

        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]

        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]


sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
