twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    date:
        format: d.m.Y, H:i
        interval_format: '%%d days'
    form_themes:
        - '@SonataCore/Form/datepicker.html.twig'
        - form/adminList/admin_list_type.html.twig
        - form/adminEquipmentKitTemplate/admin_equipment_kit_template_type.html.twig
        - form/file_type.html.twig
    paths:
        '%kernel.project_dir%/templates': app
