runtime: php73

env_variables:
  APP_ENV: prod
  APP_DEBUG: true
  APP_SECRET: YOUR_APP_SECRET
#  DATABASE_URL: 'postgres+pg8000://postgres:temerso-db-secrect@127.0.0.1/postgres?unix_sock=/cloudsql/temerso-app:us-central1:temerso-db/.s.PGSQL.5432'
#  DATABASE_URL: 'postgres://postgres:temerso-db-secrect@/postgres?unix_sock=/cloudsql/temerso-app:us-central1:temerso-db;dbname=postgres'
  DATABASE_URL: mysql://root:temerso-db-secrect@localhost?unix_socket=/cloudsql/temerso-app:us-central1:temerso-mysql;dbname=symfonydb

handlers:
  # Declare the build and bundles directory as static assets to be served by the
  # App Engine CDN.
  - url: /build
    static_dir: public/build
  - url: /bundles
    static_dir: public/bundles

  # Declare any media files in the public directory as static assets as well.
  - url: /(.*\.(ico|txt|gif|png|jpg))$
    static_files: public/\1
    upload: public/.*\.(ico|txt|gif|png|jpg)$