<?php
/**
 * Created by PhpStorm.
 * User: temerso_test
 * Date: 25.05.2020
 * Time: 13:43
 */

namespace App\Controller\Admin;


use App\Classes\ShowAdmin\ShowModeFooterActionBuilder;
use Sonata\AdminBundle\Controller\CRUDController;
use Symfony\Component\HttpFoundation\RedirectResponse;

class DefaultAdminController extends CRUDController
{
    protected function redirectTo($object)
    {
        $request = $this->getRequest();
        if ($request->get(ShowModeFooterActionBuilder::BTN_CUSTOM_REDIRECT)) {
            $param = $request->get(ShowModeFooterActionBuilder::BTN_CUSTOM_REDIRECT);
            list($routerName, $routerQuery) = explode('|', $param);
            parse_str($routerQuery, $routerQueryArray);
            $url = $this->admin->generateObjectUrl($routerName, $object, $routerQueryArray);
            return new RedirectResponse($url);
        }

        return parent::redirectTo($object); // TODO: Change the autogenerated stub
    }

}