<?php
/**
 * Created by PhpStorm.
 * User: temerso_test
 * Date: 03.05.2020
 * Time: 00:29
 */

namespace App\Form\Type;

use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\Extension\Core\Type\ButtonType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class AdminButtonTypeExtension extends AbstractTypeExtension implements \Symfony\Component\Form\FormTypeInterface
{
    public function __construct()
    {

    }

    public function getExtendedType()
    {
        return 'button';
    }

    /**
     * Add the image_path option
     *
     * @param OptionsResolver $resolver
     */
    public function setDefaultOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'sonata_field_description' => null,
                'label_render' => null,
                'property_path' => null,
                'mapped' => false
            ]
        );
    }

    /**
     * Add the image_path option
     *
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $this->setDefaultOptions($resolver);
    }

    public function getExtendedTypes()
    {
        return [ButtonType::class];
    }

    public function getBlockPrefix()
    {
        return 'button';
    }

    public function getParent()
    {
        return ButtonType::class;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $options['mapped'] = false;
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }
}